# Generated by Django 4.2.16 on 2025-11-21 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the boat", max_length=10
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="non défini",
                        help_text="Name of the boat",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Boat",
                "verbose_name_plural": "Boats",
                "db_table": "boat",
            },
        ),
        migrations.CreateModel(
            name="Cabine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the cabine", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Cabine",
                "verbose_name_plural": "Cabines",
                "db_table": "cabine",
            },
        ),
        migrations.CreateModel(
            name="GammeCabine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the gamme", max_length=10
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        help_text="reference to the boat",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.boat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gamme Cabine",
                "verbose_name_plural": "Gammes Cabine",
                "db_table": "gamme_cabine",
            },
        ),
        migrations.CreateModel(
            name="Ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the ligne", max_length=10
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="none", help_text="Name of the ligne", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne",
                "verbose_name_plural": "Lignes",
                "db_table": "ligne",
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the poste", max_length=10
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        help_text="reference to the ligne",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "db_table": "poste",
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the sheet", max_length=200),
                ),
                (
                    "business_id",
                    models.CharField(
                        help_text="Business identifier for translation", max_length=100
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code (e.g., en, fr, es)",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the sheet was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the sheet was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this sheet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet",
                "verbose_name_plural": "Sheets",
                "db_table": "sheet",
                "ordering": ["-created_at"],
                "unique_together": {("business_id", "language")},
            },
        ),
        migrations.CreateModel(
            name="VarianteGamme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="internal id of the variante", max_length=10
                    ),
                ),
                (
                    "gamme",
                    models.ForeignKey(
                        help_text="reference to the gamme",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.gammecabine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante Gamme",
                "verbose_name_plural": "Variantes Gamme",
                "db_table": "variante_gamme",
            },
        ),
        migrations.CreateModel(
            name="SheetPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        help_text="Business identifier for translation", max_length=100
                    ),
                ),
                ("number", models.IntegerField(help_text="Page number")),
                (
                    "description",
                    models.TextField(blank=True, help_text="Page description"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code (e.g., en, fr, es)",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the page was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the page was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        help_text="reference to the sheet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="production.sheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Page",
                "verbose_name_plural": "Sheet Pages",
                "db_table": "sheet_page",
                "ordering": ["sheet", "number"],
                "unique_together": {("business_id", "language")},
            },
        ),
        migrations.CreateModel(
            name="ProductionPlanningLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ligne_sens",
                    models.CharField(
                        default="D",
                        help_text="sens of the ligne: D, G or -",
                        max_length=1,
                    ),
                ),
                ("entry_date", models.DateField(help_text="entry date of the ligne")),
                ("exit_date", models.DateField(help_text="exit date of the ligne")),
                (
                    "scheduled_entry_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="scheduled entry date of the ligne",
                    ),
                ),
                (
                    "scheduled_exit_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="scheduled exit date of the ligne",
                    ),
                ),
                (
                    "cabine",
                    models.ForeignKey(
                        help_text="reference to the cabine",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.cabine",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        help_text="reference to the ligne",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.ligne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Planning Line",
                "verbose_name_plural": "Production Planning Lines",
                "db_table": "production_planning_line",
            },
        ),
        migrations.CreateModel(
            name="PosteVarianteDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ligne_sens",
                    models.CharField(
                        default="D",
                        help_text="sens of the ligne: D, G or -",
                        max_length=1,
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        help_text="reference to the poste",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.poste",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        help_text="reference to the interactive sheet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.sheet",
                    ),
                ),
                (
                    "varianteGamme",
                    models.ForeignKey(
                        help_text="reference to the variante",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.variantegamme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste Variante Documentation",
                "verbose_name_plural": "Poste Variante Documentations",
                "db_table": "poste_variante_documentation",
            },
        ),
        migrations.AddField(
            model_name="cabine",
            name="variante_gamme",
            field=models.ForeignKey(
                help_text="reference to the variante",
                on_delete=django.db.models.deletion.CASCADE,
                to="production.variantegamme",
            ),
        ),
        migrations.CreateModel(
            name="InteractiveElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        help_text="Business identifier for translation", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of interactive element", max_length=50
                    ),
                ),
                (
                    "description",
                    models.JSONField(help_text="JSON description of the element"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Language code (e.g., en, fr, es)",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the element was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the element was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this element",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_elements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="reference to the page",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="production.sheetpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Element",
                "verbose_name_plural": "Interactive Elements",
                "db_table": "interactive_element",
                "ordering": ["page", "id"],
                "unique_together": {("business_id", "language")},
            },
        ),
    ]
