# Generated by Django 4.2.16 on 2025-11-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageElement",
            fields=[
                (
                    "interactiveelement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="production.interactiveelement",
                    ),
                ),
                (
                    "url",
                    models.ImageField(
                        help_text="Upload an image file",
                        upload_to="interactive_elements/images/%Y/%m/%d/",
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Element",
                "verbose_name_plural": "Image Elements",
                "db_table": "image_element",
            },
            bases=("production.interactiveelement",),
        ),
    ]
