# Generated by Django 4.2.16 on 2025-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_imageelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelement",
            name="konva_transform",
            field=models.JSONField(
                blank=True,
                help_text="Konva.js transform data: {x, y, width, height, rotation, scaleX, scaleY, skewX, skewY, offsetX, offsetY, ...}",
                null=True,
            ),
        ),
    ]
