# Generated by Django 4.2.16 on 2025-11-22 14:04

from django.db import migrations, models
import json


def convert_descriptions_to_json(apps, schema_editor):
    """Convert existing text descriptions to JSON format based on language"""
    SheetPage = apps.get_model('production', 'SheetPage')
    
    for page in SheetPage.objects.all():
        # Get the current description and language
        old_description = page.description if page.description else ""
        language = getattr(page, 'language', 'fr')  # Default to 'fr' if no language
        
        # Create JSON structure with the description in its language
        if old_description:
            page.description_json = {language: old_description}
        else:
            page.description_json = {}
        
        page.save(update_fields=['description_json'])


def reverse_conversion(apps, schema_editor):
    """Reverse: Convert JSON back to text (use 'fr' language as default)"""
    SheetPage = apps.get_model('production', 'SheetPage')
    
    for page in SheetPage.objects.all():
        if page.description_json:
            # Try to get French description, then English, then first available
            description_dict = page.description_json if isinstance(page.description_json, dict) else {}
            page.description = description_dict.get('fr', description_dict.get('en', next(iter(description_dict.values()), '')))
        else:
            page.description = ""
        
        page.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_interactiveelement_konva_transform"),
    ]

    operations = [
        # Step 1: Add new JSON field
        migrations.AddField(
            model_name='sheetpage',
            name='description_json',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Page description in multiple languages: {'en': 'English desc', 'fr': 'Description française'}",
            ),
        ),
        
        # Step 2: Convert existing data
        migrations.RunPython(convert_descriptions_to_json, reverse_conversion),
        
        # Step 3: Remove old description field
        migrations.RemoveField(
            model_name='sheetpage',
            name='description',
        ),
        
        # Step 4: Rename new field to description
        migrations.RenameField(
            model_name='sheetpage',
            old_name='description_json',
            new_name='description',
        ),
        
        # Step 5: Update unique_together before removing fields
        migrations.AlterUniqueTogether(
            name="sheetpage",
            unique_together={("sheet", "number")},
        ),
        
        # Step 6: Remove business_id and language fields
        migrations.RemoveField(
            model_name="sheetpage",
            name="business_id",
        ),
        migrations.RemoveField(
            model_name="sheetpage",
            name="language",
        ),
    ]
