# Generated by Django 4.2.16 on 2025-11-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0004_update_sheetpage_multilingual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=50, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the tag was created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Tag",
                "verbose_name_plural": "Image Tags",
                "db_table": "image_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImageLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Image name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Image description"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image file",
                        upload_to="library_images/%Y/%m/%d/",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("fr", "French")],
                        help_text="Language for this image (optional)",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the image was uploaded"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the image was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who uploaded this image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for organizing images",
                        related_name="images",
                        to="production.imagetag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Library",
                "verbose_name_plural": "Image Library",
                "db_table": "image_library",
                "ordering": ["-created_at"],
            },
        ),
    ]
