# Generated by Django 4.2.16 on 2025-11-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0005_imagetag_imagelibrary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Reference type (e.g., 'screw', 'gabarit')",
                        max_length=50,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number, incremented on each update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reference was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the reference was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Value",
                "verbose_name_plural": "Reference Values",
                "db_table": "reference_value",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number at the time of this change"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change was made"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        help_text="JSON object describing what changed: {field_name: {old: value, new: value}}"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made this change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        help_text="Reference to the ReferenceValue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="production.referencevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference History",
                "verbose_name_plural": "Reference History",
                "db_table": "reference_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinitionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Field name (e.g., 'reference', 'image')",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Field type: 'string', 'int', 'float', or 'image'",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Language code ('en', 'fr') or NULL for non-translatable fields",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "value_string",
                    models.TextField(
                        blank=True, help_text="Value for string type", null=True
                    ),
                ),
                (
                    "value_int",
                    models.IntegerField(
                        blank=True, help_text="Value for int type", null=True
                    ),
                ),
                (
                    "value_float",
                    models.FloatField(
                        blank=True, help_text="Value for float type", null=True
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        help_text="Reference to the parent ReferenceValue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="production.referencevalue",
                    ),
                ),
                (
                    "value_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Value for image type (reference to ImageLibrary)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.imagelibrary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Definition Value",
                "verbose_name_plural": "Field Definition Values",
                "db_table": "field_definition_value",
                "ordering": ["reference", "name", "language"],
                "unique_together": {("reference", "name", "language")},
            },
        ),
    ]
