# Generated by Django 4.2.16 on 2025-11-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_add_reference_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveelement",
            name="reference_value",
            field=models.ForeignKey(
                blank=True,
                help_text="Source reference for this element (if spawned from reference library)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canvas_instances",
                to="production.referencevalue",
            ),
        ),
    ]
