# Generated by Django 4.2.16 on 2025-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_update_interactiveelement_multilingual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fielddefinitionvalue",
            options={
                "ordering": ["reference", "interactive_element", "name", "language"],
                "verbose_name": "Field Definition Value",
                "verbose_name_plural": "Field Definition Values",
            },
        ),
        migrations.AlterModelOptions(
            name="interactiveelement",
            options={
                "ordering": ["page", "z_order", "id"],
                "verbose_name": "Interactive Element",
                "verbose_name_plural": "Interactive Elements",
            },
        ),
        migrations.AddField(
            model_name="interactiveelement",
            name="z_order",
            field=models.IntegerField(
                default=0,
                help_text="Z-order for layering (higher values appear on top)",
            ),
        ),
        migrations.AlterField(
            model_name="interactiveelement",
            name="business_id",
            field=models.CharField(help_text="Business identifier", max_length=100),
        ),
    ]
