# Generated by Django 4.2.16 on 2025-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_rename_imagelibrary_to_medialibrary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medialibrary",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Media Library",
                "verbose_name_plural": "Media Library",
            },
        ),
        migrations.AlterModelOptions(
            name="mediatag",
            options={
                "ordering": ["name"],
                "verbose_name": "Media Tag",
                "verbose_name_plural": "Media Tags",
            },
        ),
        migrations.AlterUniqueTogether(
            name="sheet",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the media was uploaded"
            ),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="description",
            field=models.TextField(blank=True, help_text="Media description"),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="file",
            field=models.FileField(
                help_text="Upload a media file", upload_to="library_media/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="height",
            field=models.IntegerField(
                blank=True, help_text="Media height in pixels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fr", "French")],
                help_text="Language for this media (optional)",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="name",
            field=models.CharField(help_text="Media name", max_length=255),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the media was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="medialibrary",
            name="width",
            field=models.IntegerField(
                blank=True, help_text="Media width in pixels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="business_id",
            field=models.CharField(
                help_text="Business identifier", max_length=100, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="sheet",
            name="language",
        ),
    ]
